### ISSUE TITLE
Small screens

### ISSUE THREAD

**Issue by sphh** [SecUSo/privacy-friendly-sudoku#60] opened 2020-10-16 09:46 UTC
After the recent updates (starting with 3.0.0 and getting worse with 3.0.1) the game becomes unplayable for me:
![Screenshot_20201012-215839](https://user-images.githubusercontent.com/4856462/96243257-fe8a0780-0f93-11eb-8eaa-e1c9de559175.png)

Here are some other screenshots …
Watch the date – level overlap:
![Screenshot_20201012-215855](https://user-images.githubusercontent.com/4856462/96243280-0a75c980-0f94-11eb-9519-4424ad753747.png)

Watch the stars overflowing the borders:
![Screenshot_20201012-215849](https://user-images.githubusercontent.com/4856462/96243291-0e095080-0f94-11eb-9c81-7512de0d3803.png)

I admit, it is phone with a really small screen, but it worked with the 2.2.x series …

This is on Android 8.1 and on a Jelly Pro phone.

**Comment by emaV** [comment] 2020-10-27 07:45
I agree, the board now it's smaller. While I appreciate the ongoing development, the board size is a usability issue.

**Comment by Kamuno** [comment] 2020-10-29 08:13
Duplicate of #59

**Closed by Kamuno** 2020-10-29 08:13 UTC
